# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKLVURMkgqYSS_yu2-sedzqzbfZqd7Vn
"""

def calcular_promedio(lista_numeros):
    """
    Calcula el promedio de los números que hay en una lista.

    Esta función suma todos los números de la lista y divide el resultado
    entre la cantidad total de números, para obtener el promedio.

    Parámetros:
        lista_numeros (list): Una lista con números enteros o decimales.

    Retorna:
        float: El promedio calculado, o un mensaje de error si la lista está vacía.

    Ejemplo:
        >>> calcular_promedio([2, 4, 6])
        4.0
    """
    # Verificamos que la lista no esté vacía
    if len(lista_numeros) == 0:
        return "Error: La lista no puede estar vacía"

    # Sumamos todos los números
    suma_total = sum(lista_numeros)

    # Contamos cuántos números hay
    cantidad = len(lista_numeros)

    # Calculamos el promedio
    promedio = suma_total / cantidad

    # Devolvemos el resultado
    return promedio


# ------------------- Probamos la función -------------------
if __name__ == "__main__":
    # Creamos una lista de ejemplo
    mis_numeros = [5, 10, 5, 2]

    # Llamamos a la función y guardamos el resultado
    resultado_final = calcular_promedio(mis_numeros)

    # Mostramos el resultado en pantalla
    print("El promedio es:", resultado_final)